### ISSUE TITLE
Where is generate?

### ISSUE THREAD

**Issue by vova-malenky** [VolkovLabs/volkovlabs-abc-datasource#22]
https://github.com/VolkovLabs/volkovlabs-abc-datasource/generate missing.

**Comment by mikhail-vl** [comment]
@vova-malenky Are you logged in to GitHub? You can't generate if you are not logged in.

  Let me know.

**Comment by mikhail-vl** [comment]
I hope it worked for you. Let me know if not.

**Comment by vova-malenky** [comment]
Got it, thanks.
